# COMBINACIÓN ARCHIVOS PROCESADOS DEFUNCIONES

## 1. IMPORTAR LIBRERIAS

In [7]:
import pandas as pd
import os

## 2. DEFINIR FUNCIONES

### 2.1. Función para lectura de archivos

In [8]:
def cargar_archivos_seleccionados_con_id(ruta_carpeta, lista_archivos):
    """
    Lee los archivos .parquet especificados en 'lista_archivos' desde 'ruta_carpeta'.
    Asigna un ID incremental (1, 2, 3, ...) y crea variables globales
    con el mismo nombre del archivo (sin extensión).

    Si un archivo no se encuentra, muestra un mensaje de advertencia y continúa.
    """
    total_cargados = 0

    for idx, archivo in enumerate(lista_archivos, start=1):
        ruta = os.path.join(ruta_carpeta, archivo)
        
        # Validar existencia del archivo
        if not os.path.exists(ruta):
            print(f"⚠️ Archivo no encontrado: {archivo}")
            continue  # saltar al siguiente
        
        try:
            df = pd.read_parquet(ruta)
            df["ID"] = idx
            
            nombre_var = os.path.splitext(archivo)[0]
            globals()[nombre_var] = df  # crea variable global
            
            print(f"✅ {nombre_var} cargado con ID = {idx} ({len(df)} filas)")
            total_cargados += 1

        except Exception as e:
            print(f"❌ Error al leer {archivo}: {e}")
    
    print(f"\n📊 Archivos procesados exitosamente: {total_cargados} de {len(lista_archivos)}")

### 2.2. Función para mostrar primeros 5 registros de cada archivo cargado

In [9]:
def mostrar_head_archivos(lista_archivos):
    """
    Muestra las primeras 5 filas de cada DataFrame en memoria,
    basándose en los nombres de los archivos indicados en 'lista_archivos'.
    Si una variable no existe, muestra una advertencia y continúa.
    """
    # Mostrar todas las columnas en el output
    pd.set_option('display.max_columns', None)
    
    total_mostrados = 0

    for archivo in lista_archivos:
        nombre_var = os.path.splitext(archivo)[0]
        
        if nombre_var in globals():
            df = globals()[nombre_var]
            print(f"\n🧾 DataFrame: {nombre_var}")
            display(df.head(5))
            print("-" * 100)
            total_mostrados += 1
        else:
            print(f"⚠️ El DataFrame '{nombre_var}' no se encuentra cargado en memoria.")
    
    print(f"\n📊 Total de DataFrames mostrados: {total_mostrados} de {len(lista_archivos)}")

## 3. PROCESAMIENTO FUNCIONES

### 3.1. Leer defunciones por rangos

In [5]:
archivos_a_leer = [
    "defunciones_1979_1991_procesado.parquet",
    "defunciones_1992_1996_procesado.parquet",
    "defunciones_1997_1997_procesado.parquet",
    "defunciones_1998_2007_procesado.parquet",
    "defunciones_2008_2011_procesado.parquet",
    "defunciones_2012_2013_procesado.parquet"
]

cargar_archivos_seleccionados_con_id("data/processed", archivos_a_leer)

✅ defunciones_1979_1991_procesado cargado con ID = 1 (1869025 filas)
✅ defunciones_1992_1996_procesado cargado con ID = 2 (848360 filas)
✅ defunciones_1997_1997_procesado cargado con ID = 3 (170753 filas)
✅ defunciones_1998_2007_procesado cargado con ID = 4 (1886949 filas)
✅ defunciones_2008_2011_procesado cargado con ID = 5 (790223 filas)
✅ defunciones_2012_2013_procesado cargado con ID = 6 (402827 filas)

📊 Archivos procesados exitosamente: 6 de 6

### 3.2. Mostrar primeros 5 registros de cada archivo cargado

In [6]:
# Mostrar las primeras 5 filas de los archivos cargados
mostrar_head_archivos(archivos_a_leer)

🧾 DataFrame: defunciones_1979_1991_procesado

,COD_DPTO,COD_MUNIC,A_DEFUN,ANO,MES,SEXO,GRU_ED1,EST_CIVIL,CODPTORE,CODMUNRE,SIT_DEFUN,C_BAS1,CONS_EXP,CAU_HOMOL,NOMBRE_DEPARTAMENTO,NOMBRE_MUNICIPIO,NOMBRE_DEPARTAMENTO_RESIDENCIA,NOMBRE_MUNICIPIO_RESIDENCIA,A_DEFUN_DESC,SEXO_DESC,EST_CIVIL_DESC,SIT_DEFUN_DESC,CONS_EXP_DESC,GRU_ED1_STR,GRU_ED1_DESC,C_BAS1_DESC,CAU_HOMOL_DESC,ID
0,50,001,1,1979,01,2,14,1,50,001,1,6370,2,078,META,VILLAVICENCIO,META,VILLAVICENCIO,CABECERA MUNICIPAL,FEMENINO,SOLTERO,HOSPITAL O CLINICA,MEDICO NO TRATANTE,14,DE 35 A 39 AÑOS,ABORTO N.E.COMPLICADO POR INFECCION DEL TRACTO...,"Embarazo, parto y puerperio",1
1,50,223,1,1979,01,2,04,1,50,223,2,2762,3,043,META,CUBARRAL,META,CUBARRAL,CABECERA MUNICIPAL,FEMENINO,SOLTERO,CASA,SIN CERTIFICACIÓN MÉDICA,04,DE 1 A 5 MESES,ACIDOSIS,Todas las demás enfermedades endocrinas y nutr...,1
2,50,223,1,1979,01,2,24,1,50,223,2,2762,3,043,META,CUBARRAL,META,CUBARRAL,CABECERA MUNICIPAL,FEMENINO,SOLTERO,CASA,SIN CERTIFICACIÓN MÉDICA,24,DE 85 Y MÁS AÑOS,ACIDOSIS,Todas las demás enfermedades endocrinas y nutr...,1
3,50,683,1,1979,01,1,18,2,50,683,2,8259,3,090,META,SAN JUAN DE ARAMA,META,SAN JUAN DE ARAMA,CABECERA MUNICIPAL,MASCULINO,CASADO,CASA,SIN CERTIFICACIÓN MÉDICA,18,DE 55 A 59 AÑOS,ACC.OTRA NATUR. O NATUR. NO ESPECIF. DE VHM/PE...,Accidentes de transporte de motor y secuelas,1
4,50,287,1,1979,01,1,15,1,50,287,2,9660,3,101,META,FUENTE DE ORO,META,FUENTE DE ORO,CABECERA MUNICIPAL,MASCULINO,SOLTERO,CASA,SIN CERTIFICACIÓN MÉDICA,15,DE 40 A 44 AÑOS,"ENVEN.DERIVADOS OXAZOLIDINA:PARAMETADIONA,TRIM...",Agresiones (homicidios) y secuelas,1

----------------------------------------------------------------------------------------------------

🧾 DataFrame: defunciones_1992_1996_procesado

,COD_DPTO,COD_MUNIC,A_DEFUN,ANO,MES,SEXO,GRU_ED1,GRU_ED2,EST_CIVIL,CODPTORE,CODMUNRE,AREA_RES,PERMAN_MUN,SIT_DEFUN,C_BAS1,CONS_EXP,CAU_HOMOL,NOMBRE_DEPARTAMENTO,NOMBRE_MUNICIPIO,NOMBRE_DEPARTAMENTO_RESIDENCIA,NOMBRE_MUNICIPIO_RESIDENCIA,A_DEFUN_DESC,SEXO_DESC,EST_CIVIL_DESC,SIT_DEFUN_DESC,CONS_EXP_DESC,AREA_RES_DESC,PERMAN_MUN_DESC,GRU_ED1_STR,GRU_ED1_DESC,GRU_ED2_STR,GRU_ED2_DESC,C_BAS1_DESC,CAU_HOMOL_DESC,ID
0,08,001,1,1992,01,2,01,01,1,08,001,1,X1,4,7651,1,081,ATLÁNTICO,BARRANQUILLA,ATLÁNTICO,BARRANQUILLA,CABECERA MUNICIPAL,FEMENINO,SOLTERO,SIN INFORMACIÓN,MÉDICO TRATANTE,CABECERA,MENOS DE 1 DÍA,01,MENORES DE UN DÍA,01,MENORES DE UN AÑO,OTROS RECIEN NACIDOS A PRETERMINO,"Retardo del crecimiento fetal, desnutrición fe...",2
1,13,244,1,1992,01,2,01,01,1,13,244,1,X1,1,7400,1,088,BOLÍVAR,EL CARMEN DE BOLÍVAR,BOLÍVAR,EL CARMEN DE BOLÍVAR,CABECERA MUNICIPAL,FEMENINO,SOLTERO,HOSPITAL O CLÍNICA,MÉDICO TRATANTE,CABECERA,MENOS DE 1 DÍA,01,MENORES DE UN DÍA,01,MENORES DE UN AÑO,ANENCEFALIA,"Las demás malformaciones congénitas, deformida...",2
2,13,654,1,1992,01,1,01,01,1,13,654,1,X1,1,7400,1,088,BOLÍVAR,SAN JACINTO,BOLÍVAR,SAN JACINTO,CABECERA MUNICIPAL,MASCULINO,SOLTERO,HOSPITAL O CLÍNICA,MÉDICO TRATANTE,CABECERA,MENOS DE 1 DÍA,01,MENORES DE UN DÍA,01,MENORES DE UN AÑO,ANENCEFALIA,"Las demás malformaciones congénitas, deformida...",2
3,70,001,1,1992,01,2,01,01,1,70,001,1,X1,1,7638,2,080,SUCRE,SINCELEJO,SUCRE,SINCELEJO,CABECERA MUNICIPAL,FEMENINO,SOLTERO,HOSPITAL O CLÍNICA,MÉDICO NO TRATANTE,CABECERA,MENOS DE 1 DÍA,01,MENORES DE UN DÍA,01,MENORES DE UN AÑO,FETO O R.N. AFEC. OTRAS COMPLICACIONES DEL TRA...,Feto y recién nacido afectados por complicacio...,2
4,70,001,1,1992,01,1,01,01,1,70,001,1,X1,1,7651,1,081,SUCRE,SINCELEJO,SUCRE,SINCELEJO,CABECERA MUNICIPAL,MASCULINO,SOLTERO,HOSPITAL O CLÍNICA,MÉDICO TRATANTE,CABECERA,MENOS DE 1 DÍA,01,MENORES DE UN DÍA,01,MENORES DE UN AÑO,OTROS RECIEN NACIDOS A PRETERMINO,"Retardo del crecimiento fetal, desnutrición fe...",2

----------------------------------------------------------------------------------------------------

🧾 DataFrame: defunciones_1997_1997_procesado

,COD_DPTO,COD_MUNIC,A_DEFUN,ANO,MES,SEXO,GRU_ED1,GRU_ED2,EST_CIVIL,CODPTORE,CODMUNRE,AREA_RES,PMAN_MUER,TIEM_PER,SIT_DEFUN,C_BAS1,CONS_EXP,CAU_HOMOL,NOMBRE_DEPARTAMENTO,NOMBRE_MUNICIPIO,NOMBRE_DEPARTAMENTO_RESIDENCIA,NOMBRE_MUNICIPIO_RESIDENCIA,A_DEFUN_DESC,SEXO_DESC,EST_CIVIL_DESC,SIT_DEFUN_DESC,CONS_EXP_DESC,AREA_RES_DESC,PERMAN_MUN_DESC,PMAN_MUER_DESC,GRU_ED1_STR,GRU_ED1_DESC,GRU_ED2_STR,GRU_ED2_DESC,C_BAS1_DESC,CAU_HOMOL_DESC,ID
0,13,001,1,1997,01,2,21,06,1,13,001,1,1,72,1,J459,2,060,BOLÍVAR,CARTAGENA DE INDIAS,BOLÍVAR,CARTAGENA DE INDIAS,CABECERA MUNICIPAL,FEMENINO,SOLTERO,HOSPITAL O CLÍNICA,MÉDICO NO TRATANTE,CABECERA,72 AÑOS,NATURAL,21,DE 70 A 74 AÑOS,06,DE 65 Y MÁS AÑOS,None,Enfermedades crónicas de las vías respiratoria...,3
1,13,001,1,1997,01,2,16,05,2,13,836,1,1,00,1,I64X,2,055,BOLÍVAR,CARTAGENA DE INDIAS,BOLÍVAR,TURBACO,CABECERA MUNICIPAL,FEMENINO,CASADO,HOSPITAL O CLÍNICA,MÉDICO NO TRATANTE,CABECERA,TIEMPO DESCONOCIDO,NATURAL,16,DE 45 A 49 AÑOS,05,DE 45 A 64 AÑOS,None,Enfermedades cerebrovasculares,3
2,13,001,1,1997,01,1,21,06,2,13,001,1,1,00,1,A419,2,005,BOLÍVAR,CARTAGENA DE INDIAS,BOLÍVAR,CARTAGENA DE INDIAS,CABECERA MUNICIPAL,MASCULINO,CASADO,HOSPITAL O CLÍNICA,MÉDICO NO TRATANTE,CABECERA,TIEMPO DESCONOCIDO,NATURAL,21,DE 70 A 74 AÑOS,06,DE 65 Y MÁS AÑOS,None,"Septicemia, excepto neonatal",3
3,13,001,1,1997,01,1,16,05,1,13,001,1,1,49,1,C169,2,013,BOLÍVAR,CARTAGENA DE INDIAS,BOLÍVAR,CARTAGENA DE INDIAS,CABECERA MUNICIPAL,MASCULINO,SOLTERO,HOSPITAL O CLÍNICA,MÉDICO NO TRATANTE,CABECERA,49 AÑOS,NATURAL,16,DE 45 A 49 AÑOS,05,DE 45 A 64 AÑOS,None,Tumor maligno del estómago,3
4,13,001,1,1997,01,2,23,06,3,13,001,1,1,00,2,I259,1,051,BOLÍVAR,CARTAGENA DE INDIAS,BOLÍVAR,CARTAGENA DE INDIAS,CABECERA MUNICIPAL,FEMENINO,VIUDO,CASA,MÉDICO TRATANTE,CABECERA,TIEMPO DESCONOCIDO,NATURAL,23,DE 80 A 84 AÑOS,06,DE 65 Y MÁS AÑOS,None,Enfermedades isquémicas del corazón,3

----------------------------------------------------------------------------------------------------

🧾 DataFrame: defunciones_1998_2007_procesado

,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,COD_INST,NOM_INST,TIPO_DEFUN,ANO,MES,SEXO,EST_CIVIL,GRU_ED1,GRU_ED2,NIVEL_EDU,CODPRES,CODPTORE,CODMUNRE,AREA_RES,SEG_SOCIAL,PMAN_MUER,CONS_EXP,MU_PARTO,T_PARTO,TIPO_EMB,T_GES,PESO_NAC,EDAD_MADRE,N_HIJOSV,N_HIJOSM,EST_CIVM,NIV_EDUM,EMB_FAL,EMB_SEM,EMB_MES,MAN_MUER,CODOCUR,CODMUNOC,C_MUERTE,ASIS_MED,C_DIR1,C_ANT1,C_ANT2,C_ANT3,C_PAT1,C_BAS1,C_MCM1,CAUSA_666,CAU_HOMOL,NOMBRE_DEPARTAMENTO,NOMBRE_MUNICIPIO,NOMBRE_DEPARTAMENTO_OCURRENCIA,NOMBRE_MUNICIPIO_OCURRENCIA,NOMBRE_DEPARTAMENTO_RESIDENCIA,NOMBRE_MUNICIPIO_RESIDENCIA,A_DEFUN_DESC,SEXO_DESC,EST_CIVIL_DESC,SIT_DEFUN_DESC,CONS_EXP_DESC,AREA_RES_DESC,PMAN_MUER_DESC,TIPO_DEFUN_DESC,NIVEL_EDU_DESC,CODPRES_DESC,CODPTORE_DESC,SEG_SOCIAL_DESC,MU_PARTO_DESC,T_PARTO_DESC,TIPO_EMB_DESC,T_GES_DESC,PESO_NAC_DESC,EDAD_MADRE_DESC,N_HIJOSV_DESC,N_HIJOSM_DESC,EST_CIVM_DESC,NIV_EDUM_DESC,EMB_FAL_DESC,EMB_SEM_DESC,EMB_MES_DESC,MAN_MUER_DESC,CODOCUR_DESC,C_MUERTE_DESC,ASIS_MED_DESC,GRU_ED1_STR,GRU_ED1_DESC,GRU_ED2_STR,GRU_ED2_DESC,C_BAS1_DESC,CAU_HOMOL_DESC,C_DIR1_DESC,C_ANT1_DESC,C_ANT2_DESC,C_ANT3_DESC,C_PAT1_DESC,C_MCM1_DESC,CAUSA_666_DESC,ID
0,27,099,3,3,None,None,2,1998,04,2,1,07,02,None,170,27,099,3,9,1,4,None,None,None,None,0,0,0,0,None,None,None,None,None,None,nan,nan,4,1,NAN,NAN,NAN,NAN,NAN,A009,A009,101,001,CHOCÓ,BOJAYÁ,NO REGISTRA,NO REGISTRA,CHOCÓ,BOJAYÁ,SIN INFORMACIÓN,FEMENINO,SOLTERO,OTRO SITIO,PERSONAL DE SALUD AUTORIZADO,RURAL DISPERSO,NATURAL,DEFUNCIÓN NO FETAL,None,COLOMBIA,CHOCÓ,SIN INFORMACIÓN,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,INTERROGATORIO A FAMILIARES O TESTIGOS,SÍ,07,DE UN AÑO,02,DE 1 A 4 AÑOS,None,Enfermedades infecciosas intestinales,None,None,None,None,None,"COLERA, NO ESPECIFICADO",Enfermedades infecciosas intestinales,4
1,27,099,3,3,None,None,2,1998,04,1,1,07,02,None,170,27,099,3,9,1,4,None,None,None,None,0,0,0,0,None,None,None,None,None,None,nan,nan,4,3,NAN,NAN,NAN,NAN,NAN,A009,A009,101,001,CHOCÓ,BOJAYÁ,NO REGISTRA,NO REGISTRA,CHOCÓ,BOJAYÁ,SIN INFORMACIÓN,MASCULINO,SOLTERO,OTRO SITIO,PERSONAL DE SALUD AUTORIZADO,RURAL DISPERSO,NATURAL,DEFUNCIÓN NO FETAL,None,COLOMBIA,CHOCÓ,SIN INFORMACIÓN,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,INTERROGATORIO A FAMILIARES O TESTIGOS,IGNORADO,07,DE UN AÑO,02,DE 1 A 4 AÑOS,None,Enfermedades infecciosas intestinales,None,None,None,None,None,"COLERA, NO ESPECIFICADO",Enfermedades infecciosas intestinales,4
2,27,099,3,3,None,None,2,1998,04,1,4,15,04,9,170,27,099,3,9,1,4,None,None,None,None,0,0,0,0,None,None,None,None,None,None,nan,nan,4,3,NAN,NAN,NAN,NAN,NAN,A009,A009,101,001,CHOCÓ,BOJAYÁ,NO REGISTRA,NO REGISTRA,CHOCÓ,BOJAYÁ,SIN INFORMACIÓN,MASCULINO,"EN UNIÓN LIBRE, DIVORCIADO Y OTRO",OTRO SITIO,PERSONAL DE SALUD AUTORIZADO,RURAL DISPERSO,NATURAL,DEFUNCIÓN NO FETAL,SIN INFORMACIÓN,COLOMBIA,CHOCÓ,SIN INFORMACIÓN,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,INTERROGATORIO A FAMILIARES O TESTIGOS,IGNORADO,15,DE 35 A 39 AÑOS,04,DE 15 A 44 AÑOS,None,Enfermedades infecciosas intestinales,None,None,None,None,None,"COLERA, NO ESPECIFICADO",Enfermedades infecciosas intestinales,4
3,27,099,3,3,None,None,2,1998,04,2,1,08,02,None,170,27,099,3,9,1,4,None,None,None,None,0,0,0,0,None,None,None,None,None,None,nan,nan,4,3,NAN,NAN,NAN,NAN,NAN,A009,A009,101,001,CHOCÓ,BOJAYÁ,NO REGISTRA,NO REGISTRA,CHOCÓ,BOJAYÁ,SIN INFORMACIÓN,FEMENINO,SOLTERO,OTRO SITIO,PERSONAL DE SALUD AUTORIZADO,RURAL DISPERSO,NATURAL,DEFUNCIÓN NO FETAL,None,COLOMBIA,CHOCÓ,SIN INFORMACIÓN,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,INTERROGATORIO A FAMILIARES O TESTIGOS,IGNORADO,08,DE 2 A 4 AÑOS,02,DE 1 A 4 AÑOS,None,Enfermedades infecciosas intestinales,None,None,None,None,None,"COLERA, NO ESPECIFICADO",Enfermedades infecciosas intestinales,4
4,27,099,3,5,None,None,2,1998,04,1,4,17,05,9,170,27,099,3,9,1,4,None,None,None,None,0,0,0,0,None,None,None,None,None,None,nan,nan,4,2,NAN,NAN,NAN,NAN,NAN,A009,A009,101,001,CHOCÓ,BOJAYÁ,NO REGISTRA,NO REGISTRA,CHOCÓ,BOJAYÁ,SIN INFORMACIÓN,MASCULINO,"EN UNIÓN LIBRE, DIVORCIADO Y OTRO",None,PERSONAL DE SALUD AUTORIZADO,RURAL DISPERSO,NATURAL,DEFUNCIÓN NO FETAL,SIN INFORMACIÓN,COLOMBIA,CHOCÓ,SIN INFORMACIÓN,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,INTERROGATORIO A FAMILIARES O TESTIGOS,NO,17,DE 45 A 49 AÑOS,05,DE 45 A 64 AÑOS,None,Enfermedades infecciosas intestinales,None,None,None,None,None,"COLERA, NO ESPECIFICADO",Enfermedades infecciosas intestinales,4

----------------------------------------------------------------------------------------------------

🧾 DataFrame: defunciones_2008_2011_procesado

,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,OTRSITIODE,TIPO_DEFUN,ANO,MES,HORA,MINUTOS,SEXO,EST_CIVIL,GRU_ED1,GRU_ED2,NIVEL_EDU,ULTCURFAL,MUERTEPORO,SIMUERTEPO,OCUPACION,IDPERTET,CODPRES,CODPTORE,CODMUNRE,AREA_RES,SEG_SOCIAL,IDADMISALUD,PMAN_MUER,CONS_EXP,MU_PARTO,T_PARTO,TIPO_EMB,T_GES,T_GES_AGRU_CIE,PESO_NAC,EDAD_MADRE,N_HIJOSV,N_HIJOSM,EST_CIVM,NIV_EDUM,ULTCURMAD,EMB_FAL,EMB_SEM,EMB_MES,MAN_MUER,CODOCUR,CODMUNOC,C_MUERTE,C_MUERTEB,C_MUERTEC,C_MUERTED,C_MUERTEE,ASIS_MED,C_DIR1,C_DIR12,C_ANT1,C_ANT12,C_ANT2,C_ANT22,C_ANT3,C_ANT32,C_PAT1,C_PAT2,C_MCM1,C_BAS1,CAUSA_666,CAUSA_667,IDPROFCER,CAU_HOMOL,NOMBRE_DEPARTAMENTO,NOMBRE_MUNICIPIO,NOMBRE_DEPARTAMENTO_OCURRENCIA,NOMBRE_MUNICIPIO_OCURRENCIA,NOMBRE_DEPARTAMENTO_RESIDENCIA,NOMBRE_MUNICIPIO_RESIDENCIA,A_DEFUN_DESC,SEXO_DESC,EST_CIVIL_DESC,SIT_DEFUN_DESC,CONS_EXP_DESC,AREA_RES_DESC,PMAN_MUER_DESC,TIPO_DEFUN_DESC,NIVEL_EDU_DESC,CODPRES_DESC,CODPTORE_DESC,SEG_SOCIAL_DESC,MU_PARTO_DESC,T_PARTO_DESC,TIPO_EMB_DESC,T_GES_DESC,PESO_NAC_DESC,EDAD_MADRE_DESC,N_HIJOSV_DESC,N_HIJOSM_DESC,EST_CIVM_DESC,NIV_EDUM_DESC,EMB_FAL_DESC,EMB_SEM_DESC,EMB_MES_DESC,MAN_MUER_DESC,CODOCUR_DESC,C_MUERTE_DESC,ASIS_MED_DESC,IDADMISALUD_DESC,T_GES_AGRU_CIE_DESC,IDPROFCER_DESC,GRU_ED1_STR,GRU_ED1_DESC,GRU_ED2_STR,GRU_ED2_DESC,C_BAS1_DESC,CAU_HOMOL_DESC,C_DIR1_DESC,C_ANT1_DESC,C_ANT2_DESC,C_ANT3_DESC,C_PAT1_DESC,C_MCM1_DESC,CAUSA_666_DESC,CAUSA_667_DESC,ID
0,68,001,1,1,None,2,2008,02,04,00,1,4,25,06,99,99,9,9,None,9,170,68,001,1,9,9,2,3,None,None,None,None,None,None,None,0,0,None,None,0,None,None,None,4,68,001,1,None,None,None,None,1,T794,None,K922,None,K290,None,S720,None,R54X,None,NAN,W189,503,503,1,093,SANTANDER,BUCARAMANGA,SANTANDER,BUCARAMANGA,SANTANDER,BUCARAMANGA,CABECERA MUNICIPAL,MASCULINO,ESTABA VIUDO(A),HOSPITAL/CLÍNICA,MÉDICO LEGISTA,CABECERA MUNICIPAL,VIOLENTA,DEFUNCIÓN NO FETAL,SIN INFORMACIÓN,COLOMBIA,SANTANDER,SIN INFORMACIÓN,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,OTRO ACCIDENTE,SANTANDER,NECROPSIA,SÍ,SIN INFORMACIÓN,None,MÉDICO,25,DE 85 A 89 AÑOS,06,DE 65 Y MÁS AÑOS,None,Caídas,CHOQUE TRAUMATICO,"HEMORRAGIA GASTROINTESTINAL, NO ESPECIFICADA",GASTRITIS AGUDA HEMORRAGICA,FRACTURA DEL CUELLO DE FEMUR,None,None,Caídas,CAIDAS,5
1,68,001,1,1,None,2,2008,02,08,15,1,9,22,06,99,99,9,9,None,9,170,68,001,1,2,2,1,2,None,None,None,None,None,None,None,0,0,None,None,0,None,None,None,None,nan,nan,None,1,None,None,None,1,I249,None,I10X,None,I420,None,NAN,None,NAN,None,NAN,I249,303,303,1,051,SANTANDER,BUCARAMANGA,NO REGISTRA,NO REGISTRA,SANTANDER,BUCARAMANGA,CABECERA MUNICIPAL,MASCULINO,SIN INFORMACIÓN,HOSPITAL/CLÍNICA,MÉDICO NO TRATANTE,CABECERA MUNICIPAL,NATURAL,DEFUNCIÓN NO FETAL,SIN INFORMACIÓN,COLOMBIA,SANTANDER,SUBSIDIADO,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,None,SÍ,ENTIDAD PROMOTORA DE SALUD - SUBSIDIADO,None,MÉDICO,22,DE 70 A 74 AÑOS,06,DE 65 Y MÁS AÑOS,None,Enfermedades isquémicas del corazón,"ENFERMEDAD ISQUEMICA AGUDA DEL CORAZON, NO ESP...",None,CARDIOMIOPATIA DILATADA,None,None,None,Enfermedades isquémicas del corazón,ENFERMEDADES ISQUEMICAS DEL CORAZON,5
2,68,001,1,1,None,2,2008,02,07,50,1,6,19,05,4,99,9,9,None,9,170,68,001,1,3,5,1,3,None,None,None,None,None,None,None,0,0,None,None,0,None,None,None,None,nan,nan,1,None,None,None,None,9,R570,None,I119,None,NAN,None,NAN,None,F171,None,NAN,I119,302,302,1,050,SANTANDER,BUCARAMANGA,NO REGISTRA,NO REGISTRA,SANTANDER,BUCARAMANGA,CABECERA MUNICIPAL,MASCULINO,ESTABA CASADO(A),HOSPITAL/CLÍNICA,MÉDICO LEGISTA,CABECERA MUNICIPAL,NATURAL,DEFUNCIÓN NO FETAL,MEDIA ACADÉMICA O CLÁSICA,COLOMBIA,SANTANDER,EXCEPCIÓN,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,NECROPSIA,SIN INFORMACIÓN,ENTIDAD EXCEPTUADA DE SALUD,None,MÉDICO,19,DE 55 A 59 AÑOS,05,DE 45 A 64 AÑOS,None,Enfermedades hipertensivas,CHOQUE CARDIOGENICO,ENFERMEDAD CARDIACA HIPERTENSIVA SIN INSUF CAR...,None,None,TRAST MENTALES Y DEL COMPORTAMIENTO POR EL USO...,None,Enfermedades hipertensivas,ENFERMEDADES HIPERTENSIVAS,5
3,68,001,1,1,None,2,2008,02,01,45,1,9,22,06,99,99,9,9,None,9,170,68,001,1,2,2,1,1,None,None,None,None,None,None,None,0,0,None,None,0,None,None,None,None,nan,nan,None,1,None,None,None,1,R578,None,E878,None,NAN,None,NAN,None,N189,None,NAN,N189,612,610,1,074,SANTANDER,BUCARAMANGA,NO REGISTRA,NO REGISTRA,SANTANDER,BUCARAMANGA,CABECERA MUNICIPAL,MASCULINO,SIN INFORMACIÓN,HOSPITAL/CLÍNICA,MÉDICO TRATANTE,CABECERA MUNICIPAL,NATURAL,DEFUNCIÓN NO FETAL,SIN INFORMACIÓN,COLOMBIA,SANTANDER,SUBSIDIADO,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,None,SÍ,ENTIDAD PROMOTORA DE SALUD - SUBSIDIADO,None,MÉDICO,22,DE 70 A 74 AÑOS,06,DE 65 Y MÁS AÑOS,None,Insuficiencia renal,OTRAS FORMAS DE CHOQUE,OTROS TRAST DEL EQUILIBRIO DE ELECTROLITOS Y D...,None,None,"INSUFICIENCIA RENAL CRONICA, NO ESPECIFICADA",None,"Embarazo, parto y puerperio",CIERTAS ENFERMEDADES CRONICAS DEL HIGADO Y CIR...,5
4,68,001,1,1,None,2,2008,02,02,00,1,9,18,05,99,99,9,9,None,9,170,68,001,1,2,2,1,1,None,None,None,None,None,None,None,0,0,None,None,0,None,None,None,None,nan,nan,None,None,1,None,None,1,A419,None,K659,None,K275,None,NAN,None,NAN,None,NAN,K275,611,609,1,063,SANTANDER,BUCARAMANGA,NO REGISTRA,NO REGISTRA,SANTANDER,BUCARAMANGA,CABECERA MUNICIPAL,MASCULINO,SIN INFORMACIÓN,HOSPITAL/CLÍNICA,MÉDICO TRATANTE,CABECERA MUNICIPAL,NATURAL,DEFUNCIÓN NO FETAL,SIN INFORMACIÓN,COLOMBIA,SANTANDER,SUBSIDIADO,None,None,None,None,None,None,0 HIJOS NACIDOS VIVOS,None,None,None,None,None,None,None,None,None,SÍ,ENTIDAD PROMOTORA DE SALUD - SUBSIDIADO,None,MÉDICO,18,DE 50 A 54 AÑOS,05,DE 45 A 64 AÑOS,None,Ulcera,"SEPTICEMIA, NO ESPECIFICADA","PERITONITIS, NO ESPECIFICADA","ULCERA PEPTICA, DE SITIO NO ESPEC, CRONICA O N...",None,None,None,Hiperplasia de próstata,"APENDICITIS, HERNIA DE LA CAVIDAD ABDOMINAL Y ...",5

----------------------------------------------------------------------------------------------------

🧾 DataFrame: defunciones_2012_2013_procesado

,COD_DPTO,COD_MUNIC,A_DEFUN,SIT_DEFUN,OTRSITIODE,COD_INST,NOM_INST,TIPO_DEFUN,ANO,MES,HORA,MINUTOS,SEXO,EST_CIVIL,GRU_ED1,GRU_ED2,NIVEL_EDU,ULTCURFAL,MUERTEPORO,SIMUERTEPO,OCUPACION,IDPERTET,CODPRES,CODPTORE,CODMUNRE,AREA_RES,SEG_SOCIAL,IDADMISALU,IDCLASADMI,PMAN_MUER,CONS_EXP,MU_PARTO,T_PARTO,TIPO_EMB,T_GES,PESO_NAC,EDAD_MADRE,N_HIJOSV,N_HIJOSM,EST_CIVM,NIV_EDUM,ULTCURMAD,EMB_FAL,EMB_SEM,EMB_MES,MAN_MUER,CODOCUR,CODMUNOC,C_MUERTE,C_MUERTEB,C_MUERTEC,C_MUERTED,C_MUERTEE,ASIS_MED,C_DIR1,C_DIR12,C_ANT1,C_ANT12,C_ANT2,C_ANT22,C_ANT3,C_ANT32,C_PAT1,C_PAT2,C_BAS1,C_MCM1,IDPROFCER,CAUSA_666,CAU_HOMOL,NOMBRE_DEPARTAMENTO,NOMBRE_MUNICIPIO,NOMBRE_DEPARTAMENTO_OCURRENCIA,NOMBRE_MUNICIPIO_OCURRENCIA,NOMBRE_DEPARTAMENTO_RESIDENCIA,NOMBRE_MUNICIPIO_RESIDENCIA,A_DEFUN_DESC,SEXO_DESC,EST_CIVIL_DESC,SIT_DEFUN_DESC,CONS_EXP_DESC,AREA_RES_DESC,PMAN_MUER_DESC,TIPO_DEFUN_DESC,NIVEL_EDU_DESC,CODPRES_DESC,CODPTORE_DESC,SEG_SOCIAL_DESC,MU_PARTO_DESC,T_PARTO_DESC,TIPO_EMB_DESC,T_GES_DESC,PESO_NAC_DESC,EDAD_MADRE_DESC,N_HIJOSV_DESC,N_HIJOSM_DESC,EST_CIVM_DESC,NIV_EDUM_DESC,EMB_FAL_DESC,EMB_SEM_DESC,EMB_MES_DESC,MAN_MUER_DESC,CODOCUR_DESC,C_MUERTE_DESC,ASIS_MED_DESC,IDADMISALUD_DESC,IDPROFCER_DESC,GRU_ED1_STR,GRU_ED1_DESC,GRU_ED2_STR,GRU_ED2_DESC,C_BAS1_DESC,CAU_HOMOL_DESC,C_DIR1_DESC,C_ANT1_DESC,C_ANT2_DESC,C_ANT3_DESC,C_PAT1_DESC,C_MCM1_DESC,CAUSA_666_DESC,ID
0,76,001,1,1,None,760010379901,E.S.E. HOSPITAL UNIVERSITARIO DEL VALLE EVARIS...,2,2012,02,22,30,1,5,18,05,13,0,2,None,"PELUQUEROS, ESPECIALISTAS EN TRATAMIENTOS DE B...",6,170,76,001,1,2,2,CAPRECOM - CAJA DE PREVISION SOCIAL DE COMUNIC...,1,1,None,None,None,None,0,None,None,None,None,None,None,None,None,None,None,nan,nan,None,1,None,None,None,1,J189,None,A09,None,B378,None,N179,None,B24,None,B227,NAN,1,108,009,VALLE DEL CAUCA,SANTIAGO DE CALI,NO REGISTRA,NO REGISTRA,VALLE DEL CAUCA,SANTIAGO DE CALI,CABECERA MUNICIPAL,MASCULINO,ESTABA SOLTERO(A),HOSPITAL/CLÍNICA,MÉDICO TRATANTE,CABECERA MUNICIPAL,NATURAL,DEFUNCIÓN NO FETAL,NINGUNO,COLOMBIA,VALLE DEL CAUCA,SUBSIDIADO,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SÍ,ENTIDAD PROMOTORA DE SALUD - SUBSIDIADO,MÉDICO,18,DE 50 A 54 AÑOS,05,DE 45 A 64 AÑOS,"ENFERMEDAD POR VIH, RESULTANTE EN ENFERMEDADES...",Enfermedad por el VIH (SIDA),"NEUMONIA, NO ESPECIFICADA",DIARREA Y GASTROENTERITIS DE PRESUNTO ORIGEN I...,CANDIDIASIS DE OTROS SITIOS,"INSUFICIENCIA RENAL AGUDA, NO ESPECIFICADA","ENF POR VIRUS DE LA INMUNODEF HUMANA (VIH), SI...",None,ENFERMEDAD POR EL VIH/SIDA,6
1,19,698,3,3,None,196980001601,HOSPITAL FRANCISCO DE PAULA SANTANDER E.S.E. N...,2,2012,02,23,00,2,4,27,06,13,0,2,None,HOGAR,6,170,19,698,3,2,2,EMSSANAR ESS - ASOCIACION MUTUAL EMPRESA SOLID...,1,2,None,None,None,None,0,None,None,None,None,None,None,None,None,None,None,nan,nan,None,None,None,1,None,2,I469,None,R092,None,G936,None,NAN,None,NAN,None,G936,NAN,1,604,047,CAUCA,SANTANDER DE QUILICHAO,NO REGISTRA,NO REGISTRA,CAUCA,SANTANDER DE QUILICHAO,RURAL DISPERSO,FEMENINO,ESTABA VIUDO(A),CASA/DOMICILIO,MÉDICO NO TRATANTE,RURAL DISPERSO,NATURAL,DEFUNCIÓN NO FETAL,NINGUNO,COLOMBIA,CAUCA,SUBSIDIADO,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NO,ENTIDAD PROMOTORA DE SALUD - SUBSIDIADO,MÉDICO,27,DE 95 A 99 AÑOS,06,DE 65 Y MÁS AÑOS,EDEMA CEREBRAL,Todas las demás enfermedades del sistema nervioso,"PARO CARDIACO, NO ESPECIFICADO",PARO RESPIRATORIO,EDEMA CEREBRAL,None,None,None,"ENFERMEDADES DEL SISTEMA NERVIOSO, EXCEPTO ME...",6
2,20,001,1,1,None,200010043101,HOSPITAL ROSARIO PUMAREJO DE LOPEZ,2,2012,02,00,30,1,5,23,06,99,99,2,None,SIN INFORMACION,6,170,20,001,1,2,2,SALUDVIDA E.P.S. S.A.,1,1,None,None,None,None,0,None,None,None,None,None,None,None,None,None,None,nan,nan,None,1,None,None,None,1,J189,None,K746,None,NAN,None,NAN,None,NAN,None,K746,NAN,1,610,066,CESAR,VALLEDUPAR,NO REGISTRA,NO REGISTRA,CESAR,VALLEDUPAR,CABECERA MUNICIPAL,MASCULINO,ESTABA SOLTERO(A),HOSPITAL/CLÍNICA,MÉDICO TRATANTE,CABECERA MUNICIPAL,NATURAL,DEFUNCIÓN NO FETAL,SIN INFORMACIÓN,COLOMBIA,CESAR,SUBSIDIADO,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SÍ,ENTIDAD PROMOTORA DE SALUD - SUBSIDIADO,MÉDICO,23,DE 75 A 79 AÑOS,06,DE 65 Y MÁS AÑOS,OTRAS CIRROSIS DEL HIGADO Y LAS NO ESPECIFICADAS,Enfermedades del hígado,"NEUMONIA, NO ESPECIFICADA",OTRAS CIRROSIS DEL HIGADO Y LAS NO ESPECIFICADAS,None,None,None,None,CIERTAS ENFERMEDADES CRONICAS DEL HIGADO Y CIR...,6
3,19,001,1,1,None,190010003101,HOSPITAL UNIVERSITARIO SAN JOSE DE POPAYAN EMP...,2,2012,02,00,10,2,4,23,06,13,0,2,None,HOGAR,6,170,19,001,1,1,1,NUEVA EPS SA,1,1,None,None,None,None,0,None,None,None,None,None,None,None,None,None,None,nan,nan,None,1,1,1,None,1,C189,None,NAN,None,NAN,None,NAN,None,NAN,None,C189,NAN,1,202,014,CAUCA,POPAYÁN,NO REGISTRA,NO REGISTRA,CAUCA,POPAYÁN,CABECERA MUNICIPAL,FEMENINO,ESTABA VIUDO(A),HOSPITAL/CLÍNICA,MÉDICO TRATANTE,CABECERA MUNICIPAL,NATURAL,DEFUNCIÓN NO FETAL,NINGUNO,COLOMBIA,CAUCA,CONTRIBUTIVO,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SÍ,ENTIDAD PROMOTORA DE SALUD,MÉDICO,23,DE 75 A 79 AÑOS,06,DE 65 Y MÁS AÑOS,"TUMOR MALIGNO DEL COLON, PARTE NO ESPECIFICADA","Tumor maligno del colon, de la unión rectosigm...","TUMOR MALIGNO DEL COLON, PARTE NO ESPECIFICADA",None,None,None,None,None,T. MALIGNO DEL COLON,6
4,20,001,1,1,None,200010001801,CLINICA LAURA DANIELA LTDA,2,2012,02,20,30,1,5,03,01,13,0,None,None,None,6,170,20,001,1,2,2,SALUDVIDA E.P.S. S.A.,1,2,3,2,2,3,1,4,5,0,1,99,99,None,None,None,None,nan,nan,None,1,None,None,None,1,P261,None,P291,None,P369,None,NAN,None,NAN,None,P369,NAN,1,405,084,CESAR,VALLEDUPAR,NO REGISTRA,NO REGISTRA,CESAR,VALLEDUPAR,CABECERA MUNICIPAL,MASCULINO,ESTABA SOLTERO(A),HOSPITAL/CLÍNICA,MÉDICO NO TRATANTE,CABECERA MUNICIPAL,NATURAL,DEFUNCIÓN NO FETAL,NINGUNO,COLOMBIA,CESAR,SUBSIDIADO,DESPUÉS,CESÁREA,DOBLE,DE 28 A 37,MENOS DE 1000 GRAMOS,DE 25 A 29 AÑOS,5 HIJOS NACIDOS VIVOS,None,NO ESTABA CASADO(A) Y LLEVABA DOS O MAS AÑOS V...,SIN INFORMACIÓN,None,None,None,None,None,None,SÍ,ENTIDAD PROMOTORA DE SALUD - SUBSIDIADO,MÉDICO,03,DE 7 A 27 DÍAS,01,MENOR DE UN AÑO,"SEPSIS BACTERIANA DEL RECIEN NACIDO, NO ESPECI...",Infecciones específicas del período perinatal,HEMORRAGIA PULMONAR MASIVA ORIGINADA EN EL PER...,DISRITMIA CARDIACA NEONATAL,"SEPSIS BACTERIANA DEL RECIEN NACIDO, NO ESPECI...",None,None,None,SEPSIS BACTERIANA DEL RECIEN NACIDO,6

----------------------------------------------------------------------------------------------------

📊 Total de DataFrames mostrados: 6 de 6